### ISSUE TITLE
Vobs are missing with occlusion culling turned on

### ISSUE THREAD

**Issue by LDS1** [SaiyansKing/GD3D11#23]
Vob disappear if occlusion culling turned on

**Comment by SaiyansKing** [comment]
i'll look into it but it should be fine in v17.8-dev2.
Do they disappear completely? Occlusion use data from previous frames so vobs can appear after a few frames.

**Comment by LDS1** [comment]
I've tested on v17.8-dev2. Yep. Bushes, crates, benches and lots of other stuff just disappear and never came back. But I still see NPCs and main landscape.

**Comment by LDS1** [comment]
Couple releases back it just froze the game

**Comment by SaiyansKing** [comment]
If vobs still don't appear in [v17.8-dev2-fix1](https://github.com/SaiyansKing/GD3D11/releases/tag/v17.8-dev2-fix1) then I don't know why it doesn't work for you.

**Comment by LDS1** [comment]
Vobs are visible but appear with small delay and overall I don't see any performance improvements. 

Anyway this issue is closed, thank you

**Comment by SaiyansKing** [comment]
Since it makes query to the GPU it needs to wait for information to be available about which vobs we see and which not(so it depends on GPU power, how many frames it takes for you to see vobs). For standard render distances it probably won't get any performance and might even decrease performance but it can be useful if someone wants to use 100/100 render distances.
