### ISSUE TITLE
Huge FPS drop when shaman/seeker equip fire spell

### ISSUE THREAD

**Issue by LDS1** [SaiyansKing/GD3D11#3]
- dynamic lights (on)
- shadows (on, any starting from static)
- orc shaman goes to battle mode and equips fire spell

result:
Huge fps drop. It can go from 60+ to 10- when there are couple shamans or character is burning.
Same for skeleton mage with ice block.

**Comment by SaiyansKing** [comment]
> * dynamic lights (on)
> * shadows (on, any starting from static)
> * orc shaman goes to battle mode and equips fire spell
> 
> result: Huge fps drop. It can go from 60+ to 10- when there are couple shamans or character is burning. Same for skeleton mage with ice block.

So if I understand correctly the fps drops happen only if the dynamic shadows are on? Just so you know even though there is "static" option it doesn't work and I haven't touched dynamic shadows because I don't have any idea where to start with them.
Dynamic shadows needs a powerful GPU and even with gtx 1080 I can have fps drops to 30 when there is a lot of light sources in the scene.

**Comment by LDS1** [comment]
Nope, in my case shadows are static. 
Drop happened because of DynamicLighting turned on and fire spell used. 

Some spell effects are super resource greedy(summoning, fire and burning, ice block, maybe some other). Just holding it in hand gives me -40% fps, even worse with npc using them. 

Because of static shadows I believe there should be no additional shadow casting calculations, just possible light effects on surfaces. 

My best guess that these effects are too detailed(too many participles) or just  not optimized properly. But I'm just a web dev, I know nothing :)

**Comment by SaiyansKing** [comment]
> Nope, in my case shadows are static. Drop happened because of DynamicLighting turned on and fire spell used.
> 
> Some spell effects are super resource greedy(summoning, fire and burning, ice block, maybe some other). Just holding it in hand gives me -40% fps, even worse with npc using them.
> 
> Because of static shadows I believe there should be no additional shadow casting calculations, just possible light effects on surfaces.

That's exactly what I mean, there are two options: shadows that are casted from light that come from sun(they can only be enabled or disabled) and dynamic shadows they come from every light sources(they have 4 options: disabled, static, dynamic, full).
The static option in dynamic shadows aren't working as it should because it work the same as dynamic option.

Dynamic shadows are resource hungry since it needs to generate 6 faces of depth cube map for every light source even if the depth textures are only 64x64 pixels the geometry shader that is invoked can be heavy especially for low end gpu.

About spell effects does it happen too with the dx7 renderer that the game originally come with? Probably your gpu doesn't like the geometry shader that is used for rendering particles and the problem is that it is really simple shader.

**Comment by LDS1** [comment]
Ok, got it, thanks for the info.

DX7 is a slide show on my machine. I'm using Parallels with Win11 on ARM on macbook with m1pro.

Testing shows that spell effects per se are very fast, it's lighting that they invoke what is killing the performance. 

Is there any chance to add option that turns off DynamicLighting just for spells and leave it as is for other light sources? 
Or just turn off DynamicLighting for static shadows by default.

**Comment by LDS1** [comment]
@SaiyansKing That's what I was talking about. Ice block kills my fps, big fire spells and burning also make game unplayable. Summoning spell is somewhat taxing. Other effects are totally fine.

If the mage is dead, with dynamic lighting this location give me about 40 fps

https://youtu.be/FDO8KJ0V6Hw

**Comment by SaiyansKing** [comment]
> @SaiyansKing That's what I was talking about. Ice block kills my fps, big fire spells and burning also make game unplayable. Summoning spell is somewhat taxing. Other effects are totally fine.
> 
> If the mage is dead, with dynamic lighting this location give me about 40 fps
> 
> https://youtu.be/FDO8KJ0V6Hw

I've check it and it looks like a Zengine bug(?) instead of spawning one light point for parent it looks like it spawns light points for every particle. Without dynamic shadows point lights aren't that expensive so when it come to drawing 300-500 lights it probably won't take much of GPU processing power. You can see how the tris in scene went from 470 thousands up to 39 millions then to 16 millions. Probably can't do much here because I don't want to fix hardcoded engine bugs in this project.

**Comment by LDS1** [comment]
@dosinabox perhaps you know who can handle it? How do you think, can it be solved in scope of union or your script patch?

**Comment by LDS1** [comment]
"Fix" which disables light sources for the spells. Unpack and put into system directory. Thanks Slavemaster
[zDisableVisualLight.patch.zip](https://github.com/SaiyansKing/GD3D11/files/7739372/zDisableVisualLight.patch.zip)

**Comment by dosinabox** [comment]
> "Fix" which disables light sources for the spells(only G2). Unpack and put into system directory. Thanks Slavemaster [zDisableVisualLight.patch.zip](https://github.com/SaiyansKing/GD3D11/files/7739664/zDisableVisualLight.patch.zip)

Does it make any visible changes?

**Comment by UnresolvedExternal** [comment]
> Does it make any visible changes?
There will be no any light from any spell. Even from SPL_LIGHT.

There are a few things that can be improved here: while the spell is opening, it is recreated several times, producing 4 lights (for a time) instead of 1. In addition, the colliding projectile still has an active light source.

But if four dynamic lights are seriously degrading your performance, there isn't much to fix.

**Comment by LDS1** [comment]
> > Does it make any visible changes?
> 
> There will be no any light from any spell. Even from SPL_LIGHT.
> 
> There are a few things that can be improved here: while the spell is opening, it is recreated several times, producing 4 lights (for a time) instead of 1. In addition, the colliding projectile still has an active light source.
> 
> But if four dynamic lights are seriously degrading your performance, there isn't much to fix.

Haven't thought about the light spell... 
Can we make an exclusion for this spell and render light? It's not taxing the performance.

Overall there are just few effects that are super heavy(starting from heaviest):
- ice block (hammers fps to 0)
- fireball and burning (couple mages and burning effects can drop fps to 10(-80%))
- summoning spells (from -20% up to -50% in the moment) - not game breaking
- seekers eye destruction red mist (up to -15 fps), not game breaking
- firebolt and other small magic effects are almost fine

So, there are just 3 fps killers: iceblock and fireball + burning. Summoning also heavily drops fps, but it's not used by npcs and not that crucial. 

Is there any chance to address these specific effects?

**Comment by UnresolvedExternal** [comment]
> summoning spells (from -20% up to -50% in the moment) - not game breaking

There are no light here

> seekers eye destruction red mist (up to -15 fps), not game breaking

Dont remember this spell

[zRemoveLightFromSpells.d.zip](https://github.com/SaiyansKing/GD3D11/files/7741661/zRemoveLightFromSpells.d.zip)

Script is for G2A. Extract to System/Autorun

**Comment by lucifer602288** [comment]
> > > Does it make any visible changes?
> > 
> > 
> > There will be no any light from any spell. Even from SPL_LIGHT.
> > There are a few things that can be improved here: while the spell is opening, it is recreated several times, producing 4 lights (for a time) instead of 1. In addition, the colliding projectile still has an active light source.
> > But if four dynamic lights are seriously degrading your performance, there isn't much to fix.
> 
> Haven't thought about the light spell... Can we make an exclusion for this spell and render light? It's not taxing the performance.
> 
> Overall there are just few effects that are super heavy(starting from heaviest):
> 
>     * ice block (hammers fps to 0)
> 
>     * fireball and burning (couple mages and burning effects can drop fps to 10(-80%))
> 
>     * summoning spells (from -20% up to -50% in the moment) - not game breaking
> 
>     * seekers eye destruction red mist (up to -15 fps), not game breaking
> 
>     * firebolt and other small magic effects are almost fine
> 
> 
> So, there are just 3 fps killers: iceblock and fireball + burning. Summoning also heavily drops fps, but it's not used by npcs and not that crucial.
> 
> Is there any chance to address these specific effects?

Please write which hardware you use such as CPU, GPU, memory. Is it Linux or Windows? Which monitor resolution is used?

**Comment by LDS1** [comment]
> > summoning spells (from -20% up to -50% in the moment) - not game breaking
> 
> There are no light here
> 
> > seekers eye destruction red mist (up to -15 fps), not game breaking
> 
> Dont remember this spell
It's not a spell, it's just an effect when seekers are destroying eye in the sun circle.
> 
> [zRemoveLightFromSpells.d.zip](https://github.com/SaiyansKing/GD3D11/files/7741661/zRemoveLightFromSpells.d.zip)
> 
> Script is for G2A. Extract to System/Autorun

What changes should I expect from this?

**Comment by UnresolvedExternal** [comment]
> What changes should I expect from this?

light is removed from the only spells you mentioned

**Comment by LDS1** [comment]
> > What changes should I expect from this?
> 
> light is removed from the only spells you mentioned

Seems to be working as expected. 
>There are a few things that can be improved here: while the spell is opening, it is recreated several times, producing 4 >lights (for a time) instead of 1. In addition, the colliding projectile still has an active light source.

How do you think, will it be hard to clean up all redundant light sources from effects? Maybe it will solve the issue without turning off all the lights.

**Comment by UnresolvedExternal** [comment]
> How do you think, will it be hard to clean up all redundant light sources from effects? Maybe it will solve the issue without turning off all the lights.

I think:
1. It will help when a player or an NPC open a spell. 
2. Burning damage will kill your performance anyway.

And I am not planning to explore the problem futher. I don't use DX11 and there are more interesting tasks to do.

**Comment by LDS1** [comment]
> > How do you think, will it be hard to clean up all redundant light sources from effects? Maybe it will solve the issue without turning off all the lights.
> 
> I think:
> 
> 1. It will help when a player or an NPC open a spell.
> 2. Burning damage will kill your performance anyway.
> 
> And I am not planning to explore the problem futher. I don't use DX11 and there are more interesting tasks to do.

Thank you for the patches you've provided. It make playing with dynamic shadows possible.

**Comment by agris-codes** [comment]
This also happens when the transition to night time occurs and you are near a fixed torch. By fixed torch, I mean the braziers and sconces that use the "burning" animation to cast light. For the first 15 or so seconds after those lights are spawned, the game experiences a significant FPS drop if you are close to the lights. Then, it smooths out.

**Comment by agris-codes** [comment]
Issue also appears with Swamp Bloodflies "spit" ability, as well as the red summon VFX that surround your hands when summoning a wolf. The wolf summon FPS slowdown goes away after a few seconds, fighting swamp bloodflies is consistently laggy if they're spitting.

**Comment by LDS1** [comment]
v17.8-dev5 has `Exclude particle effects lighting from dynamic shadows rendering to avoid some performance issues due to bugged lights`, so it looks like it's not an issue anymore. Thank you guys
