### ISSUE TITLE
Draw lines using z-buffer

### ISSUE THREAD

**Issue by postm1** [SaiyansKing/GD3D11#49]
Is there any chance if you can implement a function DrawLineZ with z-buffer? (or lines culling, I don't know exactly how it is called) It would be helpful for spacer, cause right know I can't render Bbox properly cause lines does not work properly and overlap vobs and mesh.
I can see in the code you have a comment like: // TODO: Implement occlusion culling for the lines. It would be great ;)

![dx7](https://user-images.githubusercontent.com/2078377/151120640-4a0eae9a-20df-4c82-b8fb-f3d6ac6d2aa1.jpg)

**Comment by SaiyansKing** [comment]
the "occlusion culling" is for optimization to avoid unnecessary drawcalls(DX7 code already have some sort of culling so it isn't needed asap), lines have z-testing but the problem is that they are unprojected from screen coordinates(since GD3D11 works differently from DX7 and it takes world positions not screen positions for drawing) and the reconstructed world positions don't have correct z-position. I'll try to fix it, but most likely in dev5.

**Comment by SaiyansKing** [comment]
Lines should work the same as in DX7 with https://github.com/SaiyansKing/GD3D11/commit/43edbb01ec0315b8938edabfed8d2091b5b8c852
however I've changed it to work with screen-space positions directly, will look later if it is possible to get world-space position without that much precision loss that result in flickering(there is some issue with the way DX7 code projects them to screen-space positions and sometimes lines have wrong positions).

**Comment by postm1** [comment]
Thanks, I will try.

**Comment by kirides** [comment]
I tried the current master with Item locator ninja patch which draws circles using DrawLineZ.

No more flickering, circles are properly round, `toggle waynet` looks as sharp as in Dx7 and only shows "visible" waynet lines, as it should.

**Comment by postm1** [comment]
![image](https://user-images.githubusercontent.com/2078377/151704972-a8f73c13-1ba0-41e2-8f28-6f5eb5f0e9e3.png)
It works, thanks! ;)
