### ISSUE TITLE
[Suggestion to increase FPS] Don't render PFX&Decals which is not in frustum

### ISSUE THREAD

**Issue by postm1** [SaiyansKing/GD3D11#60]
A vob with PFX effect or a decal vob are rendered even if hero does not look at it (not in camera frustum)

Right now Dx11 checks only distance in **GetVisibleParticleEffectsList** and **GetVisibleDecalList** methods.
`dist > RendererState.RendererSettings.VisualFXDrawRadius` (particles & decals)

I created additional checking for that in dx11 https://github.com/SaiyansKing/GD3D11/commit/f8b37471c3434952a8ceeaec51cf3af88308c7e3  (for test only)
and set forcely showVisual = 0 in Union (c++ code) for vobs which hero can't see and **I got about 3-10 fps higher** in Khorinis in New Balance mod. (**I used showVisual property only for testing purposes, don't change it!**)

What if you add check if such vobs (PFX&Decals) are in frustrum? I mean, not adding a new check for frustum, but use the existing one: **GothicAPI::CollectVisibleVobsHelper** method

**Comment by SaiyansKing** [comment]
Hi, the problem is that any "dynamically" added object in-game isn't added to bsptree in GD3D11 code so that would require remodeling "OnAddVob" and "OnRemovedVob" functions(and I'm too lazy to touch them xD). When it comes to rendering PFX it is also rather slow due to using Geometry Shaders and they are slow(especially on older hardware).
When it comes to performance in GD3D11 there are many places where we do unnecessary buffer updates like updating GraphicsState in every HUD drawcall. Unfortunately to fix most performance issues someone would need to refactor/rewrite most of the code.

**Comment by postm1** [comment]
Ok ;)

**Comment by lucifer602288** [comment]
Where can instructions be found how to change the PFX rendering and remove the buffer updates and where in the code does the changes need to be done?

**Comment by postm1** [comment]
> Where can instructions be found how to change the PFX rendering and remove the buffer updates and where in the code does the changes need to be done?

Well, we have applied rendering optimization. In the last builds. Just don't add PFX & Decals which are not in the frustum. That is all ;) You can see the implemention in https://github.com/SaiyansKing/GD3D11/commit/2306a551be60499c462770214925b4be242ff6cb
