### ISSUE TITLE
Random cobwebs everywhere since v17.8-dev6

### ISSUE THREAD

**Issue by Kilrha** [SaiyansKing/GD3D11#63]
Ever since the new update there are random cobwebs strewn about that pop in and out of existence depending of camera position.
![random cobwebs](https://user-images.githubusercontent.com/96333422/170819760-60a7d9b3-03bc-4c26-b57b-d659bf11860e.png)
![random cobwebs 2](https://user-images.githubusercontent.com/96333422/170819764-d874ada0-6463-42fe-8726-3110d697d57a.png)

**Comment by SaiyansKing** [comment]
Hi,
actually it is an old bug that make alpha mesh vobs to be rendering two times, due to some recent code changes to updating buffers those duplicates doesn't have correct world matrix set which make them appear randomly where any vob is.
Updated [dev6](https://github.com/SaiyansKing/GD3D11/releases/tag/v17.8-dev6) with the fix for it.

**Comment by Kilrha** [comment]
Thnaks a bunch my dude! The shadows update also makes a world of difference! Thanks for making the gothic games that much more immersive!
